version: '3.8'

services:
  ai-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-chatbot-microservice
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - DATABASE_PATH=/app/data/chatbot.db
      - CORS_ORIGIN=*
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - ollama
    networks:
      - ai-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - ai-network
    # Uncomment if you have GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

networks:
  ai-network:
    driver: bridge

volumes:
  ollama_data:
    driver: local
